# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attained', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(through='award.Award', to='member.Member')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='award_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.AwardCategory'),
        ),
        migrations.AddField(
            model_name='award',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
