# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('award', '0002_remove_awardcategory_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_category', models.ManyToManyField(to='award.AwardCategory')),
            ],
        ),
    ]
