# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170622_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
    ]
